// ============================================================
//  FallGuard — ESP32 Fall Detector (50 Hz / 4 s / 200-sample window)
//  Fixes applied:
//    FIX 1  DLPF configured at 44 Hz (was unset / default undefined)
//    FIX 3  Model constants from firmware_constants.h (no manual copy-paste)
//    FIX 4  Circular buffer overread corrected in quantization loop
//    FIX 5  reset_voting() added to STATE_COOLDOWN and STATE_POST_SUPPRESS
//    FIX 6  Complementary filter replaces accelerometer-only pitch estimate
//    FIX 7  Orientation check uses Euclidean distance over pitch AND roll
//    FIX 8  User calibration adjusts MEANS_RUNTIME at startup
//    FIX 9  Telegram Bot push notification sent to iPhone on fall alarm
//    FIX 10 MPU6050 range set to ±16g / ±2000°/s to match SisFall dataset
//    FIX 11 Library output scaled to correct physical units (g / °/s)
//    FIX 12 Removed duplicate WINDOW_SIZE/N_CHANNELS (now in firmware_constants.h)
//    FIX 13 Diagnostic prints for MPU scale + quantization chain
//    FIX 14 Slow fall detection — second path for falls without impact spike
//           (faint, weakness collapse, sliding fall) using orientation change
//           relative to continuously updated upright reference
//
//  Required files in the same Arduino project folder:
//    fall_model.h          — generated by train03.py (model binary)
//    firmware_constants.h  — generated by train03.py (quantization + scaler constants)
//
//  Required Arduino libraries (install via Library Manager):
//    MPU6050_light
//    TensorFlowLite_ESP32
//    WiFi       (built-in ESP32 core — no install needed)
//    HTTPClient (built-in ESP32 core — no install needed)
// ============================================================

#include <Wire.h>
#include <WiFi.h>
#include <HTTPClient.h>
#include <MPU6050_light.h>
#include <TensorFlowLite_ESP32.h>
#include "tensorflow/lite/micro/all_ops_resolver.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_error_reporter.h"
#include "tensorflow/lite/schema/schema_generated.h"
#include "fall_model.h"

// FIX 3 — All model-derived constants come from this auto-generated header.
// Contains: INPUT_SCALE, INPUT_ZERO, OUTPUT_SCALE, OUTPUT_ZERO,
//           FALL_THRESHOLD, N_CHANNELS, MEANS[], SCALES[]
#include "firmware_constants.h"

// ============================================================
//  Hardware pins
// ============================================================
#define LED_PIN       2
#define BUZZER_PIN    27   // active buzzer (HIGH = sound)
#define BUTTON_PIN    15   // cancel button (active LOW, internal pull-up)

// ============================================================
//  FIX 10/11 — MPU6050 library scale correction
// ============================================================
const float ACC_LIB_SCALE  = 1.0f;      // library already outputs g
const float GYRO_LIB_SCALE = 1.0f;      // library already outputs °/s

// ============================================================
//  Manual gyro bias offsets (measured at startup)
// ============================================================
float gyro_bias_x = 0.0f;
float gyro_bias_y = 0.0f;
float gyro_bias_z = 0.0f;

// ============================================================
//  Firmware tuning parameters
// ============================================================
const float         LPF_ALPHA            = 0.85f;
const float         REST_SMV_MAX         = 1.15f;
const unsigned long REST_CHECK_MS        = 3000;
const int           MOVEMENT_LIMIT       = 50;
const float         ORIENT_THRESHOLD_DEG = 40.0f;
const unsigned long CONFIRM_MS           = 12000;
const int           VOTE_THRESHOLD       = 2;        // 2 out of 5 votes needed
const unsigned long COOLDOWN_MS          = 10000;
const float         MIN_IMPACT_G         = 1.0f;     // lowered for sofa falls
const unsigned long SUPPRESS_CD          = 3000;

const float         SLOW_FALL_ORIENT_DEG = 15.0f;    // lowered for testing

// ============================================================
//  Wi-Fi credentials (update before compiling)
// ============================================================
const char* WIFI_SSID     = "AZERTYY";
const char* WIFI_PASSWORD = "youtube123";

// ============================================================
//  Telegram Bot credentials (update before compiling)
// ============================================================
const char* TG_BOT_TOKEN = "7412369850:AAHxyz_AbCdEfGhIjKlMnOpQrStUvWxYz123";
const char* TG_CHAT_ID   = "987654321";

unsigned long         last_notif_ms = 0;
const unsigned long   NOTIF_CD      = 30000;

// ============================================================
//  Mutable scaler copy
// ============================================================
float MEANS_RUNTIME[N_CHANNELS];

// ============================================================
//  Complementary filter state
// ============================================================
float       cf_pitch = 0.0f;
float       cf_roll  = 0.0f;
const float CF_ALPHA = 0.98f;
const float DT       = 0.020f;   // 1 / 50 Hz

// ============================================================
//  TFLite Micro (heap-allocated arena)
// ============================================================
constexpr int  kTensorArenaSize = 48 * 1024;
static uint8_t* tensor_arena    = nullptr;

tflite::MicroErrorReporter  micro_error_reporter;
tflite::ErrorReporter*      error_reporter = &micro_error_reporter;
const tflite::Model*        tfl_model      = nullptr;
tflite::AllOpsResolver      resolver;
tflite::MicroInterpreter*   interpreter    = nullptr;
TfLiteTensor* input  = nullptr;
TfLiteTensor* output = nullptr;

// ============================================================
//  MPU-6050
// ============================================================
MPU6050 mpu(Wire);

// ============================================================
//  Circular buffer (200 samples × 8 channels)
// ============================================================
constexpr int SAMPLE_RATE_HZ  = 50;
constexpr int STEP            = 100;
constexpr int BUFFER_CAPACITY = WINDOW_SIZE * N_CHANNELS;

float*  buffer          = nullptr;
int8_t* quantized_input = nullptr;
int     buffer_head     = 0;
bool    buffer_full     = false;
int     samples_since_inference = 0;

// ============================================================
//  Voting ring buffer (last 5 probabilities)
// ============================================================
float prob_ring[5] = {0};
int   prob_idx     = 0;

// ============================================================
//  Fall state machine
// ============================================================
enum FallState {
    STATE_IDLE,
    STATE_IMPACT,
    STATE_CONFIRM,
    STATE_COOLDOWN,
    STATE_POST_SUPPRESS
};
FallState     state          = STATE_IDLE;
unsigned long state_start_ms = 0;

// ============================================================
//  HIL test mode
// ============================================================
constexpr int HIL_TOTAL_BYTES = WINDOW_SIZE * N_CHANNELS * sizeof(float);
enum HilRxState { HIL_WAIT, HIL_FILL, HIL_INFER };
HilRxState hil_rx_state = HIL_WAIT;
int        hil_bytes_rx = 0;

// ============================================================
//  Runtime state
// ============================================================
int           movement_counter = 0;
float         pitch_at_impact  = 0.0f;
float         roll_at_impact   = 0.0f;
float         upright_pitch    = 0.0f;
float         upright_roll     = 0.0f;
bool          upright_seeded   = false;
float         last_peak_g      = 0.0f;
float         last_orient_deg  = 0.0f;
bool          alarm_on         = false;
unsigned long alarm_ms         = 0;
unsigned long last_suppress_ms = 0;

// ============================================================
//  Button debounce
// ============================================================
unsigned long last_button_press = 0;
const unsigned long BUTTON_DEBOUNCE_MS = 200;

// ============================================================
//  LPF state
// ============================================================
static float ax_f = 0, ay_f = 0, az_f = 0;
static float gx_f = 0, gy_f = 0, gz_f = 0;
static bool  lpf_seeded = false;

// ============================================================
//  Utilities
// ============================================================
float compute_smv(float ax, float ay, float az) {
    return sqrtf(ax*ax + ay*ay + az*az);
}

void reset_voting() {
    for (int i = 0; i < 5; i++) prob_ring[i] = 0.0f;
    prob_idx = 0;
}

// ------------------------------------------------------------
//  Debounced button read
// ------------------------------------------------------------
bool isCancelButtonPressed() {
    if (digitalRead(BUTTON_PIN) == LOW) {
        if (millis() - last_button_press > BUTTON_DEBOUNCE_MS) {
            last_button_press = millis();
            return true;
        }
    }
    return false;
}

// ============================================================
//  Complementary filter orientation
// ============================================================
void update_orientation(float ax, float ay, float az,
                        float gx, float gy, float gz) {
    float pitch_gyro = cf_pitch + gy * DT;
    float roll_gyro  = cf_roll  + gx * DT;
    float pitch_acc  = atan2f(ax, sqrtf(ay*ay + az*az)) * (180.0f / M_PI);
    float roll_acc   = atan2f(ay, sqrtf(ax*ax + az*az)) * (180.0f / M_PI);
    cf_pitch = CF_ALPHA * pitch_gyro + (1.0f - CF_ALPHA) * pitch_acc;
    cf_roll  = CF_ALPHA * roll_gyro  + (1.0f - CF_ALPHA) * roll_acc;
}

// ============================================================
//  Wi-Fi and Telegram functions (unchanged)
// ============================================================
bool connectWiFi(unsigned long timeout_ms = 10000UL) {
    if (WiFi.status() == WL_CONNECTED) return true;
    Serial.print("Wi-Fi connecting");
    WiFi.mode(WIFI_STA);
    WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
    unsigned long start = millis();
    while (WiFi.status() != WL_CONNECTED) {
        if (millis() - start > timeout_ms) {
            Serial.println(" TIMEOUT – notification unavailable.");
            WiFi.disconnect(true);
            return false;
        }
        delay(300);
        Serial.print(".");
    }
    Serial.print(" OK. IP: ");
    Serial.println(WiFi.localIP());
    return true;
}

void sendTelegramAlert(float peak_g, float orient_deg) {
    if (last_notif_ms != 0 && millis() - last_notif_ms < NOTIF_CD) {
        Serial.println("Notification skipped – cooldown active.");
        return;
    }
    if (!connectWiFi(8000UL)) {
        Serial.println("Notification FAILED – no Wi-Fi.");
        return;
    }
    unsigned long total_s = millis() / 1000;
    unsigned long mins    = total_s / 60;
    unsigned long secs    = total_s % 60;
    String msg = String("%F0%9F%9A%A8+FALL+DETECTED%0A")
               + "Time+since+boot:+" + String(mins) + "min+" + String(secs) + "s%0A"
               + "Peak+impact:+" + String(peak_g, 2) + "g%0A"
               + "Orientation+change:+" + String(orient_deg, 1) + "%C2%B0%0A"
               + "FallGuard+is+alerting+for+help.+Please+check+on+the+person.";
    String url = String("https://api.telegram.org/bot")
               + TG_BOT_TOKEN
               + "/sendMessage?chat_id="
               + TG_CHAT_ID
               + "&text=" + msg;
    HTTPClient http;
    http.begin(url);
    http.setTimeout(8000);
    int code = http.GET();
    http.end();
    if (code == 200) {
        Serial.println("Telegram notification sent.");
        last_notif_ms = millis();
    } else {
        Serial.print("Telegram notification FAILED. HTTP code: ");
        Serial.println(code);
    }
    WiFi.disconnect(true);
}

// ============================================================
//  Alarm and warning functions (with buzzer)
// ============================================================
void start_confirm_warning() {
    digitalWrite(LED_PIN, HIGH);
    // Buzzer does NOT sound during confirmation window (only final alarm)
    Serial.println("CONFIRM WARNING – 12s to cancel");
}

void stop_confirm_warning() {
    digitalWrite(LED_PIN, LOW);
}

void start_alarm() {
    Serial.println("!!! FALL DETECTED – EMERGENCY ALERT !!!");
    digitalWrite(LED_PIN, HIGH);
    digitalWrite(BUZZER_PIN, HIGH);   // turn on buzzer
    alarm_on = true;
    alarm_ms = millis();
    sendTelegramAlert(last_peak_g, last_orient_deg);
}

void update_alarm() {
    if (alarm_on && millis() - alarm_ms >= 2000) {
        digitalWrite(LED_PIN, LOW);
        digitalWrite(BUZZER_PIN, LOW);  // turn off buzzer after 2 seconds
        alarm_on = false;
    }
}

// ============================================================
//  User calibration (gyro magnitude channel 7 excluded)
// ============================================================
void calibrate_user_offset(unsigned long duration_ms = 30000UL) {
    Serial.print("User calibration: stand still for ");
    Serial.print(duration_ms / 1000);
    Serial.println(" seconds...");

    double        sum[N_CHANNELS] = {0};
    int           count           = 0;
    unsigned long cal_start       = millis();
    unsigned long last_cal_us     = micros();

    while (millis() - cal_start < duration_ms) {
        unsigned long now_us = micros();
        if (now_us - last_cal_us >= 20000UL) {
            last_cal_us = now_us;
            mpu.update();
            float gx = (mpu.getGyroX() - gyro_bias_x) * GYRO_LIB_SCALE;
            float gy = (mpu.getGyroY() - gyro_bias_y) * GYRO_LIB_SCALE;
            float gz = (mpu.getGyroZ() - gyro_bias_z) * GYRO_LIB_SCALE;
            float ax = mpu.getAccX()  * ACC_LIB_SCALE;
            float ay = mpu.getAccY()  * ACC_LIB_SCALE;
            float az = mpu.getAccZ()  * ACC_LIB_SCALE;
            float am = sqrtf(ax*ax + ay*ay + az*az);
            float gm = sqrtf(gx*gx + gy*gy + gz*gz);
            float vals[8] = {ax, ay, az, gx, gy, gz, am, gm};
            for (int ch = 0; ch < N_CHANNELS; ch++) sum[ch] += vals[ch];
            count++;
        }
    }

    if (count == 0) {
        Serial.println("Calibration failed – using dataset MEANS.");
        return;
    }

    const float ADAPT_RATE = 0.6f;
    for (int ch = 0; ch < N_CHANNELS; ch++) {
        float user_mean = (float)(sum[ch] / count);
        if (ch == 7) {
            MEANS_RUNTIME[ch] = MEANS[ch];   // keep dataset mean for gyro magnitude
        } else {
            MEANS_RUNTIME[ch] = ADAPT_RATE * user_mean + (1.0f - ADAPT_RATE) * MEANS[ch];
        }
    }

    Serial.print("Calibration done (");
    Serial.print(count);
    Serial.print(" samples). MEANS_RUNTIME: [");
    for (int ch = 0; ch < N_CHANNELS; ch++) {
        Serial.print(MEANS_RUNTIME[ch], 4);
        if (ch < N_CHANNELS - 1) Serial.print(", ");
    }
    Serial.println("]");
}

// ============================================================
//  process_sample (50 Hz sensor processing + inference)
// ============================================================
void process_sample(float ax_raw, float ay_raw, float az_raw,
                    float gx_raw, float gy_raw, float gz_raw) {

    // NOTE: manual gyro bias subtraction is NOT used here because mpu.calcOffsets()
    // already removes the offset. The bias measurement is only for calibration.
    // If you experience drift, uncomment the following three lines:
    // gx_raw -= gyro_bias_x;
    // gy_raw -= gyro_bias_y;
    // gz_raw -= gyro_bias_z;

    // ── LPF ──────────────────────────────────────────────────────────
    if (!lpf_seeded) {
        ax_f = ax_raw; ay_f = ay_raw; az_f = az_raw;
        gx_f = gx_raw; gy_f = gy_raw; gz_f = gz_raw;
        lpf_seeded = true;
    }
    ax_f = LPF_ALPHA * ax_raw + (1.0f - LPF_ALPHA) * ax_f;
    ay_f = LPF_ALPHA * ay_raw + (1.0f - LPF_ALPHA) * ay_f;
    az_f = LPF_ALPHA * az_raw + (1.0f - LPF_ALPHA) * az_f;
    gx_f = LPF_ALPHA * gx_raw + (1.0f - LPF_ALPHA) * gx_f;
    gy_f = LPF_ALPHA * gy_raw + (1.0f - LPF_ALPHA) * gy_f;
    gz_f = LPF_ALPHA * gz_raw + (1.0f - LPF_ALPHA) * gz_f;

    // ── Complementary filter ─────────────────────────────────────────
    update_orientation(ax_f, ay_f, az_f, gx_f, gy_f, gz_f);

    // ── Update upright reference (only in IDLE, low movement) ─────────
    float smv_now_idle = sqrtf(ax_f*ax_f + ay_f*ay_f + az_f*az_f);
    if (state == STATE_IDLE && smv_now_idle < 1.3f) {
        if (!upright_seeded) {
            upright_pitch  = cf_pitch;
            upright_roll   = cf_roll;
            upright_seeded = true;
        } else {
            upright_pitch = 0.99f * upright_pitch + 0.01f * cf_pitch;
            upright_roll  = 0.99f * upright_roll  + 0.01f * cf_roll;
        }
    }

    // ── Magnitudes ───────────────────────────────────────────────────
    float acc_mag  = sqrtf(ax_f*ax_f + ay_f*ay_f + az_f*az_f);
    float gyro_mag = sqrtf(gx_f*gx_f + gy_f*gy_f + gz_f*gz_f);

    // ── Write to circular buffer ─────────────────────────────────────
    buffer[buffer_head++] = ax_f;
    buffer[buffer_head++] = ay_f;
    buffer[buffer_head++] = az_f;
    buffer[buffer_head++] = gx_f;
    buffer[buffer_head++] = gy_f;
    buffer[buffer_head++] = gz_f;
    buffer[buffer_head++] = acc_mag;
    buffer[buffer_head++] = gyro_mag;
    if (buffer_head >= BUFFER_CAPACITY) {
        buffer_head = 0;
        buffer_full = true;
    }

    // ── Inference every STEP samples (100 = 2 seconds) ───────────────
    if (buffer_full && ++samples_since_inference >= STEP) {
        samples_since_inference = 0;

        if (state == STATE_COOLDOWN || state == STATE_POST_SUPPRESS || state == STATE_CONFIRM)
            return;

        int start_idx = (buffer_head - WINDOW_SIZE * N_CHANNELS + BUFFER_CAPACITY)
                        % BUFFER_CAPACITY;

        // Quantisation
        for (int i = 0; i < WINDOW_SIZE; i++) {
            for (int ch = 0; ch < N_CHANNELS; ch++) {
                int   idx  = (start_idx + i * N_CHANNELS + ch) % BUFFER_CAPACITY;
                float norm = (buffer[idx] - MEANS_RUNTIME[ch]) / SCALES[ch];
                int32_t q  = (int32_t)roundf(norm / INPUT_SCALE) + INPUT_ZERO;
                if (q < -128) q = -128;
                if (q >  127) q =  127;
                quantized_input[i * N_CHANNELS + ch] = (int8_t)q;
            }
        }

        memcpy(input->data.int8, quantized_input,
               WINDOW_SIZE * N_CHANNELS * sizeof(int8_t));

        if (interpreter->Invoke() != kTfLiteOk) {
            Serial.println("Invoke failed");
            return;
        }

        int8_t raw_out = output->data.int8[0];
        float  prob    = ((float)raw_out - (float)OUTPUT_ZERO) * OUTPUT_SCALE;
        if (prob < 0.0f) prob = 0.0f;
        if (prob > 1.0f) prob = 1.0f;

        prob_ring[prob_idx] = prob;
        prob_idx = (prob_idx + 1) % 5;
        int votes = 0;
        for (int i = 0; i < 5; i++)
            if (prob_ring[i] >= FALL_THRESHOLD) votes++;

        Serial.print("prob="); Serial.print(prob, 3);
        Serial.print(" votes="); Serial.println(votes);

        if (votes >= VOTE_THRESHOLD && state == STATE_IDLE) {
            // Peak acceleration (channel 6)
            float peak_acc = 0.0f;
            int scan_start = (buffer_head - WINDOW_SIZE * N_CHANNELS + BUFFER_CAPACITY) % BUFFER_CAPACITY;
            for (int i = 0; i < WINDOW_SIZE; i++) {
                int idx = (scan_start + i * N_CHANNELS + 6) % BUFFER_CAPACITY;
                if (buffer[idx] > peak_acc) peak_acc = buffer[idx];
            }

            float orient_from_upright = sqrtf(
                powf(cf_pitch - upright_pitch, 2.0f) +
                powf(cf_roll  - upright_roll,  2.0f)
            );

            bool impact_fall = (peak_acc >= MIN_IMPACT_G);
            bool slow_fall   = (!impact_fall) && (orient_from_upright >= SLOW_FALL_ORIENT_DEG);

            if (!impact_fall && !slow_fall) {
                Serial.print("Votes rejected – no impact and no tilt (peak=");
                Serial.print(peak_acc, 2);
                Serial.print("g  orient_from_upright=");
                Serial.print(orient_from_upright, 1);
                Serial.println("deg)");
                reset_voting();
                return;
            }

            if (impact_fall) {
                Serial.print("IMPACT FALL – peak=");
                Serial.print(peak_acc, 2);
                Serial.print("g  orient_from_upright=");
                Serial.print(orient_from_upright, 1);
                Serial.println("deg  → 3s rest check");
            } else {
                Serial.print("SLOW FALL – peak=");
                Serial.print(peak_acc, 2);
                Serial.print("g (no impact)  orient_from_upright=");
                Serial.print(orient_from_upright, 1);
                Serial.println("deg  → 3s rest check");
            }

            pitch_at_impact  = cf_pitch;
            roll_at_impact   = cf_roll;
            last_peak_g      = peak_acc;
            movement_counter = 0;
            state            = STATE_IMPACT;
            state_start_ms   = millis();
        }
    }
}

// ============================================================
//  setup()
// ============================================================
void setup() {
    Serial.setRxBufferSize(8192);
    Serial.begin(115200);
    delay(2000);
    Serial.println("\nFallGuard — all fixes + buzzer + cancel button");

    buffer = (float*)malloc(BUFFER_CAPACITY * sizeof(float));
    quantized_input = (int8_t*)malloc(WINDOW_SIZE * N_CHANNELS * sizeof(int8_t));
    if (!buffer || !quantized_input) {
        Serial.println("Heap alloc failed!"); while (1);
    }

    pinMode(LED_PIN, OUTPUT);
    digitalWrite(LED_PIN, LOW);
    pinMode(BUZZER_PIN, OUTPUT);
    digitalWrite(BUZZER_PIN, LOW);
    pinMode(BUTTON_PIN, INPUT_PULLUP);   // internal pull-up, button to GND

    Wire.begin();

    // ---- MPU6050 init -------------------------------------------------
    Serial.println("Initializing MPU6050...");
    if (mpu.begin() != 0) {
        Serial.println("MPU6050 not found!"); while (1);
    }

    // ±16g / ±2000°/s
    Wire.beginTransmission(0x68);
    Wire.write(0x1C);
    Wire.write(0x03 << 3);
    Wire.endTransmission(true);

    Wire.beginTransmission(0x68);
    Wire.write(0x1B);
    Wire.write(0x03 << 3);
    Wire.endTransmission(true);
    Serial.println("MPU6050: ±16g accel, ±2000°/s gyro configured.");

    // DLPF 21 Hz
    Wire.beginTransmission(0x68);
    Wire.write(0x1A);
    Wire.write(0x04);
    Wire.endTransmission(true);
    Serial.println("DLPF: 21 Hz cutoff configured.");

    Serial.println("IMU offset calibration – hold still 3s...");
    delay(3000);
    mpu.calcOffsets();

    // Measure gyro bias (for calibration only)
    Serial.println("Measuring gyro bias (500 samples, keep device absolutely still)...");
    float gx_sum = 0, gy_sum = 0, gz_sum = 0;
    int bias_samples = 500;
    for (int i = 0; i < bias_samples; i++) {
        mpu.update();
        gx_sum += mpu.getGyroX();
        gy_sum += mpu.getGyroY();
        gz_sum += mpu.getGyroZ();
        delay(5);
    }
    gyro_bias_x = gx_sum / bias_samples;
    gyro_bias_y = gy_sum / bias_samples;
    gyro_bias_z = gz_sum / bias_samples;
    Serial.printf("Gyro bias (deg/s): X=%.2f, Y=%.2f, Z=%.2f\n", gyro_bias_x, gyro_bias_y, gyro_bias_z);
    Serial.println("IMU calibrated.");

    // ---- MPU6050 scale test -------------------------------------------
    Serial.println("\n--- MPU6050 SCALE TEST ---");
    Serial.println("Place device FLAT on table. Z should read ~1.0g.");
    delay(1000);
    for (int i = 0; i < 15; i++) {
        mpu.update();
        float ax = mpu.getAccX();
        float ay = mpu.getAccY();
        float az = mpu.getAccZ();
        Serial.print("Raw lib: ax="); Serial.print(ax, 3);
        Serial.print(" ay=");         Serial.print(ay, 3);
        Serial.print(" az=");         Serial.print(az, 3);
        Serial.print("  |  Scaled: ax="); Serial.print(ax * ACC_LIB_SCALE, 3);
        Serial.print(" ay=");              Serial.print(ay * ACC_LIB_SCALE, 3);
        Serial.print(" az=");              Serial.println(az * ACC_LIB_SCALE, 3);
        delay(20);
    }
    Serial.println("--- END SCALE TEST ---\n");

    // ---- TFLite Micro -------------------------------------------------
    tensor_arena = (uint8_t*)malloc(kTensorArenaSize);
    if (!tensor_arena) {
        Serial.println("tensor_arena malloc FAILED!"); while (1);
    }
    Serial.print("tensor_arena allocated: ");
    Serial.print(kTensorArenaSize / 1024);
    Serial.print(" KB  (free heap after: ");
    Serial.print(ESP.getFreeHeap());
    Serial.println(" bytes)");

    tfl_model = tflite::GetModel(fall_detector_int8_tflite);
    if (tfl_model->version() != TFLITE_SCHEMA_VERSION) {
        Serial.println("Model schema version mismatch!"); while (1);
    }

    interpreter = new tflite::MicroInterpreter(
        tfl_model, resolver, tensor_arena, kTensorArenaSize, error_reporter);

    if (interpreter->AllocateTensors() != kTfLiteOk) {
        Serial.println("AllocateTensors FAILED!"); while (1);
    }

    input  = interpreter->input(0);
    output = interpreter->output(0);
    if (!input || !output) {
        Serial.println("Tensor pointer NULL!"); while (1);
    }
    Serial.print("Model loaded – input (");
    Serial.print(WINDOW_SIZE); Serial.print(", ");
    Serial.print(N_CHANNELS); Serial.println(")");

    // ---- User calibration ---------------------------------------------
    memcpy(MEANS_RUNTIME, MEANS, N_CHANNELS * sizeof(float));
    calibrate_user_offset(5000UL);

    // ---- Wi-Fi and Telegram startup ----------------------------------
    Serial.println("Connecting to Wi-Fi...");
    if (connectWiFi(15000UL)) {
        String url = String("https://api.telegram.org/bot")
                   + TG_BOT_TOKEN
                   + "/sendMessage?chat_id="
                   + TG_CHAT_ID
                   + "&text=%E2%9C%85+FallGuard+is+online+and+monitoring."
                     "+Fall+notifications+are+active.";
        HTTPClient http;
        http.begin(url);
        http.setTimeout(8000);
        int code = http.GET();
        http.end();
        WiFi.disconnect(true);
        if (code == 200)
            Serial.println("Startup notification sent to Telegram.");
        else
            Serial.println("Startup notification failed.");
    } else {
        Serial.println("Wi-Fi unavailable – notifications disabled, detection active.");
    }

    Serial.println("\nReady. Monitoring for falls.");
    Serial.print("  Sample rate="); Serial.print(SAMPLE_RATE_HZ);
    Serial.print(" Hz  Window=");  Serial.print(WINDOW_SIZE);
    Serial.println(" samples (4 s)");
    Serial.print("  Threshold="); Serial.print(FALL_THRESHOLD, 2);
    Serial.print("  Votes=");     Serial.print(VOTE_THRESHOLD);
    Serial.print("/5  MinImpact="); Serial.print(MIN_IMPACT_G, 1);
    Serial.println("g");
}

// ============================================================
//  loop()
// ============================================================
void loop() {

    // ---- HIL state machine (unchanged) -------------------------------
    switch (hil_rx_state) {
        case HIL_WAIT:
            if (Serial.available()) {
                String cmd = Serial.readStringUntil('\n');
                cmd.trim();
                if (cmd == "HIL_START") {
                    hil_bytes_rx = 0;
                    hil_rx_state = HIL_FILL;
                    Serial.println("HIL_OK");
                } else if (cmd == "HIL_END") {
                    Serial.println("NORMAL_OK");
                }
            }
            break;

        case HIL_FILL:
            while (Serial.available() && hil_bytes_rx < HIL_TOTAL_BYTES)
                ((uint8_t*)buffer)[hil_bytes_rx++] = (uint8_t)Serial.read();
            if (hil_bytes_rx >= HIL_TOTAL_BYTES)
                hil_rx_state = HIL_INFER;
            return;

        case HIL_INFER: {
            unsigned long t0 = micros();
            for (int i = 0; i < WINDOW_SIZE; i++) {
                for (int ch = 0; ch < N_CHANNELS; ch++) {
                    float norm = buffer[i * N_CHANNELS + ch];
                    int32_t q = (int32_t)roundf(norm / INPUT_SCALE) + INPUT_ZERO;
                    if (q < -128) q = -128;
                    if (q > 127)  q = 127;
                    quantized_input[i * N_CHANNELS + ch] = (int8_t)q;
                }
            }
            memcpy(input->data.int8, quantized_input,
                   WINDOW_SIZE * N_CHANNELS * sizeof(int8_t));
            float prob = -1.0f;
            if (interpreter->Invoke() == kTfLiteOk) {
                prob = ((float)(output->data.int8[0]) - (float)OUTPUT_ZERO) * OUTPUT_SCALE;
                if (prob < 0.0f) prob = 0.0f;
                if (prob > 1.0f) prob = 1.0f;
            }
            unsigned long elapsed_us = micros() - t0;
            Serial.print("PROB:"); Serial.print(prob, 4);
            Serial.print(" INF_US:"); Serial.println(elapsed_us);
            hil_bytes_rx = 0;
            hil_rx_state = HIL_WAIT;
            return;
        }
    }

    // ---- Normal sensor loop ------------------------------------------
    update_alarm();

    static unsigned long last_sample = 0;
    unsigned long now = micros();
    if (now - last_sample >= 20000UL) {    // 50 Hz
        last_sample = now;
        mpu.update();
        process_sample(
            mpu.getAccX()  * ACC_LIB_SCALE,
            mpu.getAccY()  * ACC_LIB_SCALE,
            mpu.getAccZ()  * ACC_LIB_SCALE,
            mpu.getGyroX() * GYRO_LIB_SCALE,
            mpu.getGyroY() * GYRO_LIB_SCALE,
            mpu.getGyroZ() * GYRO_LIB_SCALE
        );
    }

    // ---- Fall state machine (with button cancellation) --------------
    switch (state) {

        case STATE_IMPACT: {
            int li = (buffer_head - N_CHANNELS + BUFFER_CAPACITY) % BUFFER_CAPACITY;
            float smv_now = compute_smv(buffer[li], buffer[li+1], buffer[li+2]);

            if (smv_now > REST_SMV_MAX) movement_counter++;
            else if (movement_counter > 0) movement_counter--;

            if (movement_counter >= MOVEMENT_LIMIT) {
                float orient_delta_sup = sqrtf(
                    powf(cf_pitch - pitch_at_impact, 2.0f) +
                    powf(cf_roll  - roll_at_impact,  2.0f)
                );
                if (orient_delta_sup < ORIENT_THRESHOLD_DEG) {
                    state = STATE_POST_SUPPRESS;
                    state_start_ms = millis();
                    movement_counter = 0;
                    reset_voting();
                    if (millis() - last_suppress_ms > SUPPRESS_CD) {
                        Serial.print("Suppressed – upright, orient_delta=");
                        Serial.print(orient_delta_sup, 1);
                        Serial.println("deg");
                        last_suppress_ms = millis();
                    }
                } else {
                    movement_counter = 0;
                    Serial.print("Movement ignored – tilted ");
                    Serial.print(orient_delta_sup, 1);
                    Serial.println("deg → possible real fall");
                }
                break;
            }

            if (millis() - state_start_ms >= REST_CHECK_MS) {
                float orient_delta = sqrtf(
                    powf(cf_pitch - pitch_at_impact, 2.0f) +
                    powf(cf_roll  - roll_at_impact,  2.0f)
                );
                last_orient_deg = orient_delta;
                Serial.print("Orient delta: ");
                Serial.print(orient_delta, 1);
                Serial.println(" deg");
                if (orient_delta >= ORIENT_THRESHOLD_DEG)
                    Serial.println("  → tilt confirmed (fall evidence)");
                start_confirm_warning();
                state = STATE_CONFIRM;
                state_start_ms = millis();
                reset_voting();
                Serial.println("Rest OK – 12s cancellation window open.");
            }
            break;
        }

        case STATE_CONFIRM: {
            // Blink LED at 1.25 Hz
            if ((millis() / 400) % 2) digitalWrite(LED_PIN, HIGH);
            else                       digitalWrite(LED_PIN, LOW);

            // Check cancel button
            if (isCancelButtonPressed()) {
                Serial.println("Alarm cancelled by user.");
                stop_confirm_warning();
                digitalWrite(BUZZER_PIN, LOW);   // ensure buzzer off
                state = STATE_IDLE;
                reset_voting();
                break;
            }

            if (millis() - state_start_ms >= CONFIRM_MS) {
                stop_confirm_warning();
                start_alarm();      // this turns on buzzer and LED, sends Telegram
                state = STATE_COOLDOWN;
                state_start_ms = millis();
            }
            break;
        }

        case STATE_COOLDOWN:
            if (millis() - state_start_ms >= COOLDOWN_MS) {
                reset_voting();
                state = STATE_IDLE;
                Serial.println("Cooldown done – ready.");
            }
            break;

        case STATE_POST_SUPPRESS:
            if (millis() - state_start_ms >= 2000) {
                reset_voting();
                state = STATE_IDLE;
                Serial.println("Post-suppress done – ready.");
            }
            break;

        default: break;
    }
}