// ================================================================
// AUTO-GENERATED by train03_fixed.py — DO NOT EDIT MANUALLY.
// Generated : 2026-05-22 22:43:01
// Regenerate: re-run train03_fixed.py after any model change.
// ================================================================
#ifndef FIRMWARE_CONSTANTS_H
#define FIRMWARE_CONSTANTS_H

// --- TFLite INT8 quantization parameters ---
constexpr float INPUT_SCALE    = 0.16009723f;
constexpr int   INPUT_ZERO     = -2;
constexpr float OUTPUT_SCALE   = 0.00390625f;
constexpr int   OUTPUT_ZERO    = -128;

// --- Detection threshold (from dual-constraint val+static search) ---
constexpr float FALL_THRESHOLD = 0.49f;

// --- Channel / window constants ---
constexpr int   N_CHANNELS     = 8;
constexpr int   WINDOW_SIZE    = 200; // 200 samples @ 50 Hz = 4 seconds

// --- StandardScaler parameters from pre01.py ---
constexpr float MEANS [N_CHANNELS] = {-0.704273f, -0.131104f, -0.024831f, 2.423183f, -0.272546f, -1.373038f, 1.730170f, 37.266091f};
constexpr float SCALES[N_CHANNELS] = {0.605865f, 0.485938f, 2.562555f, 36.592298f, 29.453422f, 29.190286f, 2.165691f, 40.959039f};

#endif  // FIRMWARE_CONSTANTS_H
